# Generated by Django 3.1b1 on 2021-05-06 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('other_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.PositiveIntegerField()),
                ('home_address', models.CharField(max_length=100)),
                ('contact_address', models.CharField(max_length=100)),
                ('LGA_of_origin', models.CharField(max_length=100)),
                ('state_of_origin', models.CharField(max_length=100)),
                ('Gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=7)),
                ('course', models.CharField(choices=[('Choose...', 'Choose...'), ('AI', 'Artificial Intelligence'), ('WB', 'Web Development'), ('ML', 'Machine Learning'), ('DL', 'Deep Learning'), ('RB', 'Robotics'), ('APP', 'App Development'), ('CP', 'Computer Programming'), ('GD', 'Graphic Design'), ('WP', 'Word Processing')], max_length=100)),
                ('t_and_c', models.BooleanField(default=False)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='picture')),
                ('image1', models.ImageField(upload_to='picture')),
                ('description', models.TextField()),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_rendered', models.CharField(max_length=100)),
                ('pics', models.ImageField(upload_to='picture')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UsersComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('suggestion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=50)),
                ('profile_pic', models.FileField(upload_to='')),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='wholphin.courses')),
            ],
        ),
        migrations.CreateModel(
            name='CoursesDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_subtitle', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wholphin.courses')),
            ],
            options={
                'verbose_name_plural': "Courses' Detail",
            },
        ),
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wholphin.courses')),
            ],
            options={
                'verbose_name_plural': 'Course Amount',
            },
        ),
    ]
