# Generated by Django 3.1b1 on 2021-05-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholphin', '0002_coursesdetail_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='amount',
            field=models.PositiveIntegerField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='duration',
            field=models.PositiveIntegerField(default=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Amount',
        ),
    ]
