# Generated by Django 3.1b1 on 2021-05-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholphin', '0003_auto_20210506_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('other_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.PositiveIntegerField()),
                ('home_address', models.CharField(max_length=100)),
                ('contact_address', models.CharField(max_length=100)),
                ('LGA_of_origin', models.CharField(max_length=100)),
                ('state_of_origin', models.CharField(choices=[('ab', 'Abia'), ('ada', 'Adamawa'), ('aks', 'Akwa Ibom'), ('bau', 'Bauchi'), ('bay', 'Bayelsa'), ('ben', 'Benue'), ('bor', 'Borno'), ('crs', 'Cross River'), ('del', 'Delta'), ('ebo', 'Ebonyi'), ('Ed', 'Edo'), ('Eki', 'Ekiti'), ('Enu', 'Enugu'), ('Gom', 'Gombe'), ('Im', 'Imo'), ('Jiga', 'Jigawa'), ('Kadu', 'Kaduna'), ('Kan', 'Kano'), ('Kat', 'Katsina'), ('Keb', 'Kebbi'), ('Kog', 'Kogi'), ('Kwa', 'Kwara'), ('Lag', 'Lagos'), ('Nasa', 'Nasarawa'), ('Nig', 'Niger'), ('Ogu', 'Ogun'), ('Ond', 'Ondo'), ('Osu', 'Osun'), ('Oy', 'Oyo'), ('Pla', 'Plateau'), ('Rs', 'Rivers'), ('Sok', 'Sokoto'), ('Tara', 'Taraba'), ('Yob', 'Yobe'), ('Zamfa', 'Zamfara'), ('FCT', 'Abuja')], max_length=100)),
                ('Gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=7)),
                ('course', models.CharField(choices=[('Choose...', 'Choose...'), ('AI', 'Artificial Intelligence'), ('WB', 'Web Development'), ('ML', 'Machine Learning'), ('DL', 'Deep Learning'), ('RB', 'Robotics'), ('APP', 'App Development'), ('CP', 'Computer Programming'), ('GD', 'Graphic Design'), ('WP', 'Word Processing')], max_length=100)),
                ('t_and_c', models.BooleanField(default=False)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Student Registered',
            },
        ),
        migrations.DeleteModel(
            name='CourseRegistration',
        ),
    ]
