# Generated by Django 3.1b1 on 2021-05-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholphin', '0004_auto_20210506_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistered',
            name='passport',
            field=models.ImageField(default=True, upload_to='picture'),
            preserve_default=False,
        ),
    ]
