# Generated by Django 3.1b1 on 2021-05-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholphin', '0005_studentregistered_passport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistered',
            name='passport',
            field=models.FileField(upload_to='picture'),
        ),
    ]
