# Generated by Django 3.1b1 on 2021-05-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholphin', '0006_auto_20210507_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistered',
            name='passport',
            field=models.ImageField(upload_to='picture'),
        ),
    ]
