# Generated by Django 3.1b1 on 2021-05-10 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wholphin', '0007_auto_20210510_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentregistered',
            name='passport',
        ),
    ]
