# Generated by Django 3.1b1 on 2021-05-10 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wholphin', '0008_remove_studentregistered_passport'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Products',
        ),
    ]
