# Generated by Django 3.1b1 on 2021-05-11 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wholphin', '0010_auto_20210511_1356'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductDetail',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
