# Generated by Django 3.1b1 on 2021-06-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholphin', '0011_auto_20210511_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistered',
            name='state_of_origin',
            field=models.CharField(choices=[('Choose...', 'Choose...'), ('ab', 'Abia'), ('ada', 'Adamawa'), ('aks', 'Akwa Ibom'), ('bau', 'Bauchi'), ('bay', 'Bayelsa'), ('ben', 'Benue'), ('bor', 'Borno'), ('crs', 'Cross River'), ('del', 'Delta'), ('ebo', 'Ebonyi'), ('Ed', 'Edo'), ('Eki', 'Ekiti'), ('Enu', 'Enugu'), ('Gom', 'Gombe'), ('Im', 'Imo'), ('Jiga', 'Jigawa'), ('Kadu', 'Kaduna'), ('Kan', 'Kano'), ('Kat', 'Katsina'), ('Keb', 'Kebbi'), ('Kog', 'Kogi'), ('Kwa', 'Kwara'), ('Lag', 'Lagos'), ('Nasa', 'Nasarawa'), ('Nig', 'Niger'), ('Ogu', 'Ogun'), ('Ond', 'Ondo'), ('Osu', 'Osun'), ('Oy', 'Oyo'), ('Pla', 'Plateau'), ('Rs', 'Rivers'), ('Sok', 'Sokoto'), ('Tara', 'Taraba'), ('Yob', 'Yobe'), ('Zamfa', 'Zamfara'), ('FCT', 'Abuja')], max_length=100),
        ),
    ]
