# Generated by Django 3.1b1 on 2021-05-12 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='order',
        ),
    ]
