# Generated by Django 3.1b1 on 2021-05-13 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_ordernow'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordernow',
            name='order',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='products.products'),
            preserve_default=False,
        ),
    ]
