# Generated by Django 3.1b1 on 2021-05-13 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210513_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordernow',
            name='order',
        ),
    ]
