# Generated by Django 3.1b1 on 2021-05-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210513_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordernow',
            name='order',
            field=models.CharField(choices=[('Choose...', 'Choose...'), ('AI ECOMMERCE', 'AI Ecommerce Software'), ('AI HEALTH', 'AI Healthcare Software'), ('AI FINANCE', 'AI Finance Software'), ('ROBOTIC', 'Robotics'), ('IMAGE RECOG.', 'Image Recognition Software'), ('CHATBOT', 'Chatterbot'), ('AI MARKETING', 'AI Marketing Software'), ('RESEARCH', 'Research Project'), ('WEBSITE', 'Responsive Websites')], max_length=30),
        ),
        migrations.AlterField(
            model_name='products',
            name='service_rendered',
            field=models.CharField(max_length=100),
        ),
    ]
