# Generated by Django 3.1b1 on 2021-06-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_it'),
    ]

    operations = [
        migrations.AlterField(
            model_name='it',
            name='cgpa',
            field=models.FloatField(),
        ),
    ]
