# Generated by Django 3.1b1 on 2021-06-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20210604_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='it',
            old_name='fullname',
            new_name='full_name',
        ),
        migrations.AlterField(
            model_name='it',
            name='level',
            field=models.CharField(choices=[('Choose...', 'Choose....'), ('300L', '300 Level'), ('400L', '400 Level'), ('Nd', 'ND'), ('Hnd', 'HND')], max_length=30),
        ),
    ]
