# Generated by Django 3.1b1 on 2021-06-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20210604_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='it',
            name='duration',
            field=models.CharField(choices=[('Choose...', 'Choose....'), ('3M', '3 Months'), ('6M', '6 Months'), ('12M', '12 Months')], max_length=20),
        ),
    ]
