# Generated by Django 3.1b1 on 2021-06-04 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20210604_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='it',
            name='date_ordered',
        ),
    ]
