# Generated by Django 3.1b1 on 2021-06-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20210604_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('contact_address', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('Choose...', 'Choose....'), ('MALE', 'Male'), ('FEMALE', 'Female')], max_length=20)),
                ('dob', models.DateField()),
                ('state', models.CharField(choices=[('ab', 'Abia'), ('ada', 'Adamawa'), ('aks', 'Akwa Ibom'), ('bau', 'Bauchi'), ('bay', 'Bayelsa'), ('ben', 'Benue'), ('bor', 'Borno'), ('crs', 'Cross River'), ('del', 'Delta'), ('ebo', 'Ebonyi'), ('Ed', 'Edo'), ('Eki', 'Ekiti'), ('Enu', 'Enugu'), ('Gom', 'Gombe'), ('Im', 'Imo'), ('Jiga', 'Jigawa'), ('Kadu', 'Kaduna'), ('Kan', 'Kano'), ('Kat', 'Katsina'), ('Keb', 'Kebbi'), ('Kog', 'Kogi'), ('Kwa', 'Kwara'), ('Lag', 'Lagos'), ('Nasa', 'Nasarawa'), ('Nig', 'Niger'), ('Ogu', 'Ogun'), ('Ond', 'Ondo'), ('Osu', 'Osun'), ('Oy', 'Oyo'), ('Pla', 'Plateau'), ('Rs', 'Rivers'), ('Sok', 'Sokoto'), ('Tara', 'Taraba'), ('Yob', 'Yobe'), ('Zamfa', 'Zamfara'), ('FCT', 'Abuja')], max_length=30)),
                ('LGA', models.CharField(max_length=30)),
                ('educational_qualification', models.CharField(choices=[('Ssce', 'SSCE'), ('Nd', 'ND'), ('Hnd', 'HND'), ('BSc', 'BSc/BEng'), ('MASTERS', 'Masters')], max_length=100)),
                ('jod_title', models.CharField(choices=[('PHPWEB', 'PHP Web Developer'), ('DJANGOWEB', 'Django Web Developer'), ('APP DEVELOPER', 'App Developer'), ('SOFTWARE DEVELOPER', 'Software Developer'), ('AI DEVELOPER', 'Artificial Intelligent Engineer'), ('ELECT/ELECT', 'Electrical/Electronic Engineer'), ('RECEPTIONIST', 'Receptionist'), ('DATA_SCIENTIST', 'Data Scientist'), ('FRONT_END_DEV.', 'Front End Developer'), ('MACHINE LEARNING ENGR,', 'Machine Learning Engineer'), ('PYTHON_DEV', 'Python Developer')], max_length=100)),
                ('resume', models.FileField(upload_to='Resumes')),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Job Application',
            },
        ),
    ]
