# Generated by Django 3.1b1 on 2021-06-08 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='resume',
        ),
    ]
