# Generated by Django 3.1b1 on 2021-06-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_remove_application_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='it',
            name='nationality',
            field=models.CharField(default=True, max_length=30),
            preserve_default=False,
        ),
    ]
