# Generated by Django 3.1b1 on 2021-06-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_it_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='it',
            name='passport',
            field=models.ImageField(default=True, upload_to='IT'),
            preserve_default=False,
        ),
    ]
