# Generated by Django 3.1b1 on 2021-06-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_it_passport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='it',
            name='passport',
            field=models.ImageField(blank=True, null=True, upload_to='IT'),
        ),
    ]
