# Generated by Django 3.1b1 on 2021-06-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_passport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='img',
            field=models.FileField(upload_to='passport'),
        ),
    ]
