# Generated by Django 3.1b1 on 2021-06-17 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20210617_1103'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Passport',
        ),
    ]
