# Generated by Django 3.1b1 on 2021-06-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_delete_passport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passoport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='passport')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
