# Generated by Django 3.1b1 on 2021-06-21 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_passoport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Passoport',
        ),
    ]
